name: MANYUU
description: A social network mobile app
version: 1.0.0
homepage: https://example.com
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true